Update tracks.html
Hamakor/AugustPenguin pull request #125
Opened 2017-07-18 10:12 UTC by marmor

2017-07-18 10:15 UTC, tbrisker requested changes

2017-07-18 10:15 UTC, tbrisker commented on en/tracks.html
> +
looks like a mistake?

2017-07-18 10:24 UTC, marmor commented
אופס, שברתי משהו?
מיד בודק, עמך הסליחה!

On Tue, Jul 18, 2017 at 1:15 PM, Tomer Brisker <notifications@github.com>
wrote:

> *@tbrisker* requested changes on this pull request.
> ------------------------------
>
> In en/tracks.html
> <https://github.com/Hamakor/AugustPenguin/pull/125#discussion_r127935799>:
>
> > @@ -183,7 +183,9 @@ <h1 id="tracks">Track List</h1>
>      </div> <!-- end tracks-content -->
>
>      <div id="footer">
> -      cc-by-sa <a href="http://hamakor.org.il">Hamakor</a>. Design by <a href="http://tomercohen.com">Tomer Cohen</a>, graphics by <a href="http://sijp.co.il">Shlomi Israely</a>, font by <a href="http://culmus.sf.net">Culmus project</a>.
> +      cc-by-sa <a href="http://
> +	
>
> looks like a mistake?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Hamakor/AugustPenguin/pull/125#pullrequestreview-50566433>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABMxoSni-Mc8BSBNER9yoLYzHaNC1p-yks5sPIXEgaJpZM4ObINi>
> .
>

2017-07-18 10:25 UTC, marmor commented on en/tracks.html
> +
Indeed!

2017-07-20 16:55 UTC, tbrisker commented
Merged as 6c0192be27889d5a20b27f4b0299d26d4438dcda, Thanks @marmor !

2017-07-20 16:55 UTC, closed without merging